[general]
YOUTUBE_VIDEO_ID = ""
ADMIN_EMAIL = "arshadpashaintern@gmail.com"
ADMIN_NAME = "Arshad"

[auth]
redirect_uri = "http://localhost:8501/oauth-callback"
cookie_secret = "randomly-generated-secret-string-for-security"

[auth.google]
client_id = "954147246487-ogeec8m680fd5782ctp43kicpur6gugo.apps.googleusercontent.com"
client_secret = "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"
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"

[api_key]
GEMINI_API_KEY = "AIzaSyAvZLy3IXlXTcTZyc8dQq7NNc0aDh0XwK8"
NASA_API_KEY = "bNkRZC5UQO6g0a7BqstdvptZSSSzRkHVoAOVdYjC"
NEWS_API_KEY = "3c2ab745f20d4dad8f55576e77344c34"
OpenAI_API_KEY="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"
SPOONACULAR_API_KEY="847291f8ec484613a3b9b7af63b366b5"
TMDB_API_KEY="9db5f820"  # Using OMDb API key instead of TMDB
UBERDUCK_API_KEY="1cfdef3292e793cd939edb45c23db14c92f6c960a9ff133981b2f27b06abc9dc032445ec8cc1e602de613fd188d1c7b7"
VISION_API_KEY="a1002f8fcd7a20c9fd74062ba34ba9d1"  # arshad check it if not works
WEATHER_API_KEY="a1002f8fcd7a20c9fd74062ba34ba9d1"
WOLFRAM_API_KEY="62XX4T-25HJP9AA43"
YOUTUBE_API_KEY="AIzaSyA_--DvifTVH3nv0u1g2GusD9ZpE3OScO0"

[spotify]
SPOTIFY_CLIENT_ID = "e36dd7688b784a5b93536df114becf28"
SPOTIFY_CLIENT_SECRET = "728d94e26ba74a62b8d9152bd1bd8968"

[kaggle]
KAGGLE_USERNAME = "arshadpasha65"
KAGGLE_KEY = "e595e90a5797e1814c66c9b159e8f0cf"

[dogBreedClassificationModel]
MODEL="1O0vm50puB3FpWWpS53mB1_FazCRJXjvp"

[SERVICES]
SERPAPI_API_KEY = "e68b75481c686f1eccca342c6d03f5b2ddc19eb6f9b4b6a1f243364065d06dba"
NEWS_API_KEY = "3c2ab745f20d4dad8f55576e77344c34"